steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/product-service:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/product-service:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - product-service
      - --image=us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/product-service:latest
      - --region=us-central1
      - --platform=managed
      - --service-account=gym-run-sa@ensayo1-494921.iam.gserviceaccount.com
      - --add-cloudsql-instances=ensayo1-494921:us-central1:gym-postgres
      - --no-allow-unauthenticated
      - --set-env-vars=DB_HOST=34.135.17.99,DB_PORT=5432,DB_NAME=gym_product_db,DB_USER=gym_user,DB_SCHEMA=catalog,KAFKA_BOOTSTRAP_SERVERS=disabled
      - --set-secrets=DB_PASSWORD=db-password:latest,JWT_SECRET=jwt-secret:latest

images:
  - us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/product-service:latest