apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
  namespace: gym-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      containers:
        - name: category-service
          image: gym/category-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: DB_NAME
              value: gym_category_db
            - name: DB_SCHEMA
              value: catalog
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 25
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: gym-inventory
spec:
  selector:
    app: category-service
  ports:
    - port: 8082
      targetPort: 8082

