apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: gym-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: gym/inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: DB_NAME
              value: gym_inventory_db
            - name: DB_SCHEMA
              value: inventory
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 25
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: gym-inventory
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8084
      targetPort: 8084

