apiVersion: v1
kind: Secret
metadata:
  name: platform-secret
  namespace: gym-inventory
type: Opaque
stringData:
  DB_USER: gym
  DB_PASSWORD: gym
  JWT_SECRET: replace-this-with-a-very-strong-secret-32-bytes
  BOOTSTRAP_ADMIN_PASSWORD: Admin123!

