apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: gym-inventory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # 🔥 bajado (5Gi es innecesario en dev)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gym-inventory
spec:
  replicas: 1

  # 🔥 IMPORTANTE: evita conflictos de volumen
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          # 🔥 FIX CLAVE: recursos BAJOS (esto te estaba rompiendo todo)
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi

          env:
            - name: POSTGRES_DB
              value: postgres

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: platform-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secret
                  key: DB_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

        - name: postgres-init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gym-inventory
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432