apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: gym-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: us-central1-docker.pkg.dev/gym-inventory-platform/gym-backend/product-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080   # 🔥 CORREGIDO
          env:
            - name: DB_NAME
              value: gym_product_db
            - name: DB_SCHEMA
              value: product
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080   # 🔥 CORREGIDO
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080   # 🔥 CORREGIDO
            initialDelaySeconds: 90
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: gym-inventory
spec:
  selector:
    app: product-service
  ports:
    - port: 8080        # 🔥 CORREGIDO
      targetPort: 8080  # 🔥 CORREGIDO