steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/user-service:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/user-service:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - user-service
      - --image=us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/user-service:latest
      - --region=us-central1
      - --platform=managed
      - --service-account=gym-run-sa@ensayo1-494921.iam.gserviceaccount.com
      - --add-cloudsql-instances=ensayo1-494921:us-central1:gym-postgres
      - --no-allow-unauthenticated
      - --set-env-vars=DB_HOST=34.135.17.99,DB_PORT=5432,DB_NAME=gym_user_db,DB_USER=gym_user,DB_SCHEMA=identity,JWT_ISSUER=gym-inventory,JWT_EXPIRATION_MINUTES=480,BOOTSTRAP_ADMIN_USERNAME=admin,BOOTSTRAP_ADMIN_EMAIL=admin@gym.com
      - --set-secrets=DB_PASSWORD=db-password:latest,JWT_SECRET=jwt-secret:latest,BOOTSTRAP_ADMIN_PASSWORD=bootstrap-admin-password:latest

images:
  - us-central1-docker.pkg.dev/ensayo1-494921/gym-repo/user-service:latest